# Generated by Django 3.1.7 on 2021-04-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210429_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock_updated',
        ),
    ]
