# Generated by Django 3.1.7 on 2021-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_top_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_products',
            old_name='name',
            new_name='Name_of_product',
        ),
        migrations.RenameField(
            model_name='top_products',
            old_name='image',
            new_name='image_of_product',
        ),
    ]
