# Generated by Django 3.1.7 on 2021-04-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210429_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default='No video', upload_to='uploads/videos/'),
        ),
    ]
